django/1031_all_of_crud_prac/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    # <값정의:변수명>
    path('<int:pk>/', views.detail, name='detail'),
]

django/1031_all_of_crud_prac/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    image = models.ImageField(blank=True, upload_to='%Y/%m/%d/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title

django/1031_all_of_crud_prac/articles/forms.py
from django import forms
from .models import Article

# Form에는 두가지 종류가 있는데, Model에 대한 정보의 유/무 를 기준으로 나눈다.
class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ('title', 'content', 'image',)

django/1031_all_of_crud_prac/articles/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_safe
from .models import Article
from .forms import ArticleForm

# Create your views here.
#get요청일때만
@require_safe
def index(request):
    # 모든 게시물들을 보여줄 것
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles
    }
    # render 함수를 2번째 인자 문자열 경로는 실제 파일이 저장되어 있는 경로를 의미,templates는 생략
    return render(request, 'articles/index.html', context)

def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = ArticleForm()
    context = {
        'form': form
    }
    return render(request, 'articles/create.html', context)

def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    context = {
        'article': article
    }
    return render(request, 'articles/detail.html', context)

django/1031_all_of_crud_prac/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block title %}
  CREATE
{% endblock title %}

{% block content %}
  <h1>CREATE PAGE</h1>
  <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Submit</button>
  </form>
  <a href="{% url 'articles:index' %}">INDEX</a>
{% endblock content %}

django/1031_all_of_crud_prac/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  DETAIL
{% endblock title %}

{% block content %}
  <h1>DETAIL PAGE</h1>
  <p>{{article.pk}}번째 글</p>
  <p>제목 : {{article.title}}</p>
  <p>내용 : {{article.content}}</p>
  <p>{{article.image}}</p>
  <img src="{% static 'articles/2021/10/31/지슬.png' %}" alt="">
  <p>생성시간 : {{article.created_at}}</p>
  <p>수정시간 : {{article.updated_at}}</p>

{% endblock content %}

django/1031_all_of_crud_prac/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block title %}
  INDEX
{% endblock title %}

{% block content %}
  <a href="{% url 'articles:create' %}">CREATE</a>
  <h1>INDEX PAGE</h1>
  {% for article in articles %}
    <p>{{ article.pk }}번 째</p>
      <p>
        <a href="{% url 'articles:detail' article.pk %}">
          {{ article.title }}
        </a>
      </p>
    <hr>
  {% empty %}
    <p>게시글이 없어용</p>
  {% endfor %}
{% endblock content %}